
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'schemaCOMMA IDENT INPUT INVENT LPAREN RPARENschema : relation_listrelation_list : directive_relation\n            | relation_list directive_relationdirective_relation : INPUT relation\n            | INVENT relation\n            | relationrelation : IDENT LPAREN type_list RPARENtype_list : type\n            | type COMMA type_listtype : IDENT'
    
_lr_action_items = {'INPUT':([0,2,3,5,8,9,10,15,],[4,4,-2,-6,-3,-4,-5,-7,]),'INVENT':([0,2,3,5,8,9,10,15,],[6,6,-2,-6,-3,-4,-5,-7,]),'IDENT':([0,2,3,4,5,6,8,9,10,11,15,16,],[7,7,-2,7,-6,7,-3,-4,-5,12,-7,12,]),'$end':([1,2,3,5,8,9,10,15,],[0,-1,-2,-6,-3,-4,-5,-7,]),'LPAREN':([7,],[11,]),'COMMA':([12,14,],[-10,16,]),'RPAREN':([12,13,14,17,],[-10,15,-8,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'schema':([0,],[1,]),'relation_list':([0,],[2,]),'directive_relation':([0,2,],[3,8,]),'relation':([0,2,4,6,],[5,5,9,10,]),'type_list':([11,16,],[13,17,]),'type':([11,16,],[14,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> schema","S'",1,None,None,None),
  ('schema -> relation_list','schema',1,'p_schema','parser.py',9),
  ('relation_list -> directive_relation','relation_list',1,'p_relation_list','parser.py',14),
  ('relation_list -> relation_list directive_relation','relation_list',2,'p_relation_list','parser.py',15),
  ('directive_relation -> INPUT relation','directive_relation',2,'p_directive_relation','parser.py',23),
  ('directive_relation -> INVENT relation','directive_relation',2,'p_directive_relation','parser.py',24),
  ('directive_relation -> relation','directive_relation',1,'p_directive_relation','parser.py',25),
  ('relation -> IDENT LPAREN type_list RPAREN','relation',4,'p_relation','parser.py',35),
  ('type_list -> type','type_list',1,'p_type_list','parser.py',40),
  ('type_list -> type COMMA type_list','type_list',3,'p_type_list','parser.py',41),
  ('type -> IDENT','type',1,'p_type','parser.py',49),
]
